<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>9c3edd9e-1f68-4760-bcb7-57d9220ff275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addTask']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addTask</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c6faa8b2-3068-4ea9-9cc8-f4266bfddf1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field mat-raised-button mat-button-base mat-primary cdk-focused cdk-mouse-focused</value>
      <webElementGuid>a8a9ca81-f38a-454e-9a5a-5ed469a117f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>73ca3299-7186-4d17-adae-d4911e1db769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addTask</value>
      <webElementGuid>246b5901-ff3f-4879-ad6c-3d27072a3871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>58be8edc-8f5c-47f9-98c0-f57269a8794c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>0bb4bb5f-cd25-4b9e-a108-fe3d5ae8be6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add </value>
      <webElementGuid>f4c01cb1-1d0c-4f6d-b280-8d92de23ff12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addTask&quot;)</value>
      <webElementGuid>67486bcd-a8a7-458d-b5b8-f328e8d34619</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addTask']</value>
      <webElementGuid>2d5eed39-79af-4e0b-8cfe-b8fd9bbde480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task due date'])[1]/following::button[2]</value>
      <webElementGuid>719211a7-be28-4196-bea1-a86ecfe7eed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Task 1'])[1]/preceding::button[1]</value>
      <webElementGuid>83fa048a-8318-45b0-a933-0f1188ca6474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card-actions/button</value>
      <webElementGuid>c876cd04-d633-46df-b30e-d8fdd91f0aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'addTask' and @type = 'submit' and (text() = ' Add ' or . = ' Add ')]</value>
      <webElementGuid>38f321d5-f516-44dc-bb10-056f6704f583</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
