<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Test Task 1_cdk-overlay-backdrop mat-ov_99e93d</name>
   <tag></tag>
   <elementGuidId>27a9eb44-7bd7-4385-b33b-5186a4414ebc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cdk-overlay-backdrop.mat-overlay-transparent-backdrop.cdk-overlay-backdrop-showing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>93220fdc-dde6-45eb-bdba-a76b1d6178fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cdk-overlay-backdrop mat-overlay-transparent-backdrop cdk-overlay-backdrop-showing</value>
      <webElementGuid>29efcc81-6ac5-451e-8ee7-b0dd497f727b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;cdk-overlay-container&quot;]/div[@class=&quot;cdk-overlay-backdrop mat-overlay-transparent-backdrop cdk-overlay-backdrop-showing&quot;]</value>
      <webElementGuid>4fa7f0b7-608c-44e1-a38d-e3367b373a78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>3c225713-bf1e-4db8-92db-0032ff7a27e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
