<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_app-view</name>
   <tag></tag>
   <elementGuidId>654bdc52-d892-4bef-9034-0b2ec5df6701</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.app-view</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e47afac3-9f8c-4ae9-bd58-d7b65e456bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-view</value>
      <webElementGuid>455edc70-a31a-45db-bdc8-b21351a11c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;app-view&quot;]</value>
      <webElementGuid>df64ebe9-0c17-4bdb-8eda-ffd5eb1f1ec4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>b0bec670-30db-49e3-91e6-4759afd9676a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
