<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login to manage your tasks EmailPasswor_198fb6</name>
   <tag></tag>
   <elementGuidId>3c8f89b7-9797-4950-8a3c-29aa17dce36c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.login-page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-login-page/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf72d513-9d34-4973-a7ce-f11396e5a916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-page</value>
      <webElementGuid>8a03de68-779b-43b8-8203-7a4c8fefbecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayout</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>443fa2ab-22be-4c94-bc3f-a9133f196815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayout.xs</name>
      <type>Main</type>
      <value>column</value>
      <webElementGuid>ad9352c5-e6dc-41d5-9c1e-627b6488faf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayoutalign</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>f9268a97-3cbf-41a6-8e37-67d43e5e92ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayoutgap</name>
      <type>Main</type>
      <value>50px</value>
      <webElementGuid>a4e82ab5-90f8-4628-8e30-e40bb8fda29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-layout</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>794fb104-742e-47d8-9ebd-6172ad5ee69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-layout.xs</name>
      <type>Main</type>
      <value>column</value>
      <webElementGuid>bcc5d12f-a880-454f-b239-b9d726f34e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-layout-gap</name>
      <type>Main</type>
      <value>50px</value>
      <webElementGuid>71c09f56-3f14-4152-b67d-3f0b7f0b0264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-layout-align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>d0f7e949-623a-4c4a-8752-9cfbba00dbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login to manage your tasks EmailPasswordWrong Credentials! Login </value>
      <webElementGuid>a658dbe5-a110-4c2f-bc10-cdfc79c6b2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;app-view&quot;]/app-login-page[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;login-page&quot;]</value>
      <webElementGuid>71dc728a-1501-4fbb-b98a-aa97cc6bddc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-login-page/div</value>
      <webElementGuid>b0d16a59-ae59-4bd0-bcec-f3e9ada3cfd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Login to manage your tasks EmailPasswordWrong Credentials! Login ' or . = ' Login to manage your tasks EmailPasswordWrong Credentials! Login ')]</value>
      <webElementGuid>8d22ea62-2133-4368-b8d2-9a99e82e1196</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
