<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-card_Login to manage your tasks EmailPa_3bda32</name>
   <tag></tag>
   <elementGuidId>758232d2-3e82-4df1-882e-efaf2d2342f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-card</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-card.mat-card</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-card</value>
      <webElementGuid>b91b0094-fe61-4fdd-8beb-2f385b613016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-card</value>
      <webElementGuid>15ce9bcf-a235-4a19-8bc5-7844332755b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflexalign</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>0ae1b2d3-a187-49f7-be0c-849a2d01d2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-flex-align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>dd60cb73-14bf-4428-96ee-eb3a10dc7c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login to manage your tasks EmailPassword Login </value>
      <webElementGuid>399d6750-eeff-4c34-9f6d-8c05a2ee041c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;app-view&quot;]/app-login-page[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;login-page&quot;]/mat-card[@class=&quot;mat-card&quot;]</value>
      <webElementGuid>75a28241-d5bd-4827-85e6-7006b534c80f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card</value>
      <webElementGuid>c70118c2-94f2-492f-b846-1ca34fb87ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-card[(text() = ' Login to manage your tasks EmailPassword Login ' or . = ' Login to manage your tasks EmailPassword Login ')]</value>
      <webElementGuid>46babbe7-be62-4511-8d53-6ce855082a39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
